# Generated by Django 4.1.5 on 2023-01-21 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(blank=True, max_length=128, null=True, verbose_name='نام کاربری')),
                ('password', models.CharField(blank=True, max_length=128, null=True, verbose_name='پسوورد')),
                ('phone', models.CharField(max_length=30, unique=True, verbose_name='تلفن')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
                ('is_admin', models.BooleanField(default=False, verbose_name='ادمین')),
                ('is_client', models.BooleanField(default=False, verbose_name='کلاینت')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
            },
        ),
    ]
