# Generated by Django 4.1.5 on 2023-01-21 09:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprequest',
            name='request_id',
            field=models.UUIDField(default=uuid.UUID('cbce9bcf-88ab-4ecb-a361-fe0f5a94693c'), editable=False, primary_key=True, serialize=False),
        ),
    ]
